# Generated by Django 2.1.3 on 2019-03-08 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 22, 13, 11, 437758), verbose_name='date published'),
        ),
    ]
